//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenteSLandingP
    {
        public int ID_Agente { get; set; }
        public int ID_Page { get; set; }
        public string Dominio_Page { get; set; }
    
        public virtual AgenteSeguro AgenteSeguro { get; set; }
        public virtual LandingPage LandingPage { get; set; }
    }
}
