//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenteSeguro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgenteSeguro()
        {
            this.AgenteSLandingPs = new HashSet<AgenteSLandingP>();
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int ID_Agente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Foto_logo { get; set; }
        public string CorreoElectronico_1 { get; set; }
        public string CorreoElectronico_2 { get; set; }
        public string CorreoElectronico_3 { get; set; }
        public string Telefono_1 { get; set; }
        public string Telefono_2 { get; set; }
        public string Telefono_3 { get; set; }
        public string Telefono_4 { get; set; }
        public string Telefono_5 { get; set; }
        public bool WhatsAPP { get; set; }
        public string DireccionCorta { get; set; }
        public string Dir_Estado { get; set; }
        public string Dir_MuniDele { get; set; }
        public string Dir_Colonia { get; set; }
        public string Dir_Calle { get; set; }
        public string Dir_NoInt { get; set; }
        public string Dir_NoExt { get; set; }
        public string Dir_CP { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string LinkedIn { get; set; }
        public string Twitter { get; set; }
        public string Youtube { get; set; }
        public string Dominio { get; set; }

        public int Campo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgenteSLandingP> AgenteSLandingPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
