//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandingPage()
        {
            this.AgenteSLandingPs = new HashSet<AgenteSLandingP>();
        }
    
        public int ID_Page { get; set; }
        public string Dominio_Page { get; set; }
        public int Plantilla { get; set; }
        public int Color { get; set; }
        public int Imagen { get; set; }
        public string Titulo_Profesional { get; set; }
        public string Mensaje_1 { get; set; }
        public string Mensaje_2 { get; set; }
        public string Aseguradora_1 { get; set; }
        public string Aseguradora_2 { get; set; }
        public string Aseguradora_3 { get; set; }
        public string Aseguradora_4 { get; set; }
        public string Aseguradora_5 { get; set; }
        public string Aseguradora_6 { get; set; }
        public string Aseguradora_7 { get; set; }

        public string Ramo { get; set; }

        public int Campo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgenteSLandingP> AgenteSLandingPs { get; set; }
    }
}
