//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UkuviTecEntities1 : DbContext
    {
        public UkuviTecEntities1()
            : base("name=UkuviTecEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgenteSeguro> AgenteSeguros { get; set; }
        public virtual DbSet<AgenteSLandingP> AgenteSLandingPs { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DatoRequerido> DatoRequeridoes { get; set; }
        public virtual DbSet<LandingPage> LandingPages { get; set; }
        public virtual DbSet<Seguro> Seguroes { get; set; }
    }
}
